version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: nest_postgres
    restart: always

    environment:
      POSTGRES_DB: nest_db
      POSTGRES_USER: nest_user
      POSTGRES_PASSWORD: nest_password

    ports:
      - "5436:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
