services:
  postgresql:
    image: postgres
    container_name: lesson
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=lesson
      - POSTGRES_PASSWORD=lesson
      - POSTGRES_DB=lesson
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgresql_data:
